version: 2
jobs:
  build:
    branches:
      - master
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Listing directory
          command: pwd && ls -lah
      - run:
          name: Installing Dependencies
          command: dnf install git -y 
      - run:
          name: Checkout to gh-pages
          command: git checkout -b gh-pages
      - run:
          name: Remove README and .circleci
          command: rm -r README.md .circleci
      - run:
          name: Extract src content
          command: mv src/* .
      - run:
          name: Remove old src file
          command: rm -r src
      - run:
          name: Git add and commit
          command: git add . && git commit -m ':poop: Circle CI'
      - run:
          name: Pushing
          command: git push origin gh-pages
 
